name: Tests
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      # The CKAN version tag of the Solr and Postgres containers should match
      # the one of the container the tests run on.
      # You can switch this base image with a custom image tailored to your project
      image: openknowledge/ckan-dev:2.9
    services:
      solr:
        image: ckan/ckan-solr:2.9-solr9-spatial
      postgres:
        image: ckan/ckan-postgres-dev:2.9
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
          image: redis:7-alpine

    env:
      CKAN_SQLALCHEMY_URL: postgresql://ckan_default:pass@postgres/ckan_test
      CKAN_DATASTORE_WRITE_URL: postgresql://datastore_write:pass@postgres/datastore_test
      CKAN_DATASTORE_READ_URL: postgresql://datastore_read:pass@postgres/datastore_test
      CKAN_SOLR_URL: http://solr:8983/solr/ckan
      CKAN_REDIS_URL: redis://redis:6379/1

    steps:
    - uses: actions/checkout@v4
    - name: Install requirements
      # Install any extra requirements your extension has here (dev requirements, other extensions etc)
      run: |
        # Install general requirements
        pip install --no-cache-dir -r requirements.txt
        pip install --no-cache-dir -r dev-requirements.txt
        pip install --no-cache-dir -e .
        
        # Install ckanext-dcat
        pip install --no-cache-dir -e git+https://github.com/mjanez/ckanext-dcat.git@v1.6.0#egg=ckanext-dcat
        pip install --no-cache-dir -r https://raw.githubusercontent.com/mjanez/ckanext-dcat/v1.6.0/requirements.txt

        # Install ckanext-harvest
        pip install --no-cache-dir -e git+https://github.com/ckan/ckanext-harvest.git@v1.5.6#egg=ckanext-harvest
        pip install --no-cache-dir -r https://raw.githubusercontent.com/ckan/ckanext-harvest/v1.5.6/requirements.txt

        # Install ckanext-scheming
        pip install --no-cache-dir -e git+https://github.com/ckan/ckanext-scheming.git@release-3.0.0#egg=ckanext-scheming

        # Install ckanext-schemingdcat
        pip install --no-cache-dir -e git+https://github.com/mjanez/ckanext-schemingdcat.git@v3.2.0#egg=ckanext_schemingdcat 
        pip install --no-cache-dir -r https://raw.githubusercontent.com/mjanez/ckanext-schemingdcat/v3.2.0/requirements.txt

        # Install ckanext-fluent
        pip install --no-cache-dir -e git+https://github.com/mjanez/ckanext-fluent.git@v1.0.1#egg=ckanext-fluent

        # Install ckanext-sparql_interface
        pip install --no-cache-dir -e git+https://github.com/OpenDataGIS/ckanext-sparql_interface.git@2.0.3-iepnb#egg=ckanext-sparql_interface && \
        pip install --no-cache-dir -r https://raw.githubusercontent.com/OpenDataGIS/ckanext-sparql_interface/2.0.3-iepnb/requirements.txt

    - name: Setup extension
      # Extra initialization steps
      run: |
        # Replace default path to CKAN core config file with the one on the container
        sed -i -e 's/use = config:.*/use = config:\/srv\/app\/src\/ckan\/test-core.ini/' test.ini
        ckan -c test.ini db init
    - name: Run tests
      run: pytest --ckan-ini=test.ini --cov=ckanext.iepnb --disable-warnings ckanext/iepnb